<?php

namespace Mints\MPublic\Config;

trait PublicFolders
{
    /**
     * Get public folders.
     * Get a collection of public folders.
     *
     * @param array|null $options List of Single Resource Options shown above can be used as parameter.
     *
     * @return mixed
     */
    public function getPublicFolders($options = null)
    {
        return $this->client->raw('get', '/config/public-folders', $options);
    }

    /**
     * Get public folder.
     * Get a public folder info.
     *
     * @param string $slug    It's the string identifier generated by Mints.
     * @param array  $options List of Single Resource Options shown above can be used as parameter.
     *
     * @return mixed
     */
    public function getPublicFolder($slug, $options)
    {
        return $this->client->raw('get', "/config/public-folders/{$slug}", $options);
    }
}