<?php

namespace Mints\MPublic\Config;

trait PublicTags
{
    /**
     * Get tags.
     * Get a collection of tags.
     *
     * @param array|null $options List of Resource collection Options shown above can be used as parameter.
     *
     * @return mixed
     */
    public function getTags($options = null)
    {
        return $this->client->raw('get', '/config/tags', $options);
    }

    /**
     * Get tag.
     * Get a single tag.
     *
     * @param string $slug    It's the string identifier generated by Mints.
     * @param array  $options List of Single Resource Options shown above can be used as parameter.
     *
     * @return mixed
     */
    public function getTag($slug, $options = null)
    {
        return $this->client->raw('get', "/config/tags/{$slug}", $options);
    }
}