<?php

namespace Mints\MPublic\Ecommerce;

use Mints\MintsHelper;

trait PublicProductVersions
{
    /**
     * Get Product Versions.
     * Get a collection of product versions.
     *
     * @param array|null $options List of Resource collection options shown above can be used as parameter.
     * @param bool $usePost Variable to determine if the request is by 'post' or 'get' functions.
     * @return mixed
     * @throws \Exception
     */
    public function getProductVersions($options = null, $usePost = true)
    {
        return MintsHelper::getQueryResults($this->client, '/ecommerce/product-versions', $options, $usePost);
    }

    /**
     * Get Product Version.
     * Get a single product version.
     *
     * @param string $slug It's the string identifier generated by Mints.
     * @param array|null $options List of Single Resource options shown above can be used as parameter.
     * @return mixed
     * @throws \Exception
     */
    public function getProductVersion($slug, $options = null)
    {
        return $this->client->raw('get', "/ecommerce/product-versions/{$slug}", $options);
    }
}