<?php

namespace Mints\MPublic\Content;

trait PublicContentInstanceVersions
{
    /**
     * Get Content Instance Versions.
     * Get a collection of content instance versions.
     *
     * @param array|null $options List of Resource collection options shown above can be used as parameter.
     * @return mixed
     * @throws \Exception
     */
    public function getContentInstanceVersions($options = null)
    {
        if (!isset($options['template'])) {
            throw new \Exception('Error 422 | Missing required fields, Add the template option, example { template: slug }');
        }

        return $this->client->raw('get', '/content/content-instance-versions', $options);
    }

    /**
     * Get Content Instance Version.
     * Get a single content instance version.
     *
     * @param string $slug It's the string identifier generated by Mints.
     * @param array|null $options List of Single Resource options shown above can be used as parameter.
     * @return mixed
     * @throws \Exception
     */
    public function getContentInstanceVersion($slug, $options = null)
    {
        return $this->client->raw('get', "/content/content-instance-versions/{$slug}", $options);
    }
}