<?php

namespace Mints\MPublic\Content;

use Mints\MintsHelper;

trait PublicStories
{
    /**
     * Get Stories.
     * Get a collection of stories.
     *
     * @param array|null $options List of Resource collection options shown above can be used as parameter.
     * @param bool $usePost Variable to determine if the request is by 'post' or 'get' functions.
     * @return mixed
     * @throws \Exception
     */
    public function getStories($options = null, $usePost = true)
    {
        return MintsHelper::getQueryResults($this->client, '/content/stories', $options, $usePost);
    }

    /**
     * Get Story.
     * Get a single story.
     *
     * @param string $slug It's the string identifier generated by Mints.
     * @param array|null $options List of Single Resource options shown above can be used as parameter.
     * @return mixed
     * @throws \Exception
     */
    public function getStory($slug, $options = null)
    {
        return $this->client->raw('get', "/content/stories/{$slug}", $options);
    }
}