<?php

namespace Mints\MPublic\Content;

trait PublicContentBundles
{
    /**
     * Get Content Pages.
     * Get all content pages.
     *
     * @param array|null $options List of Resource collection options shown above can be used as parameter.
     * @return mixed
     * @throws \Exception
     */
    public function getContentBundles($options = null)
    {
        return $this->client->raw('get', '/content/content-bundles', $options);
    }

    /**
     * Get Content Page.
     * Get a single content page.
     *
     * @param string $slug It's the string identifier generated by Mints.
     * @param array|null $options
     * @return mixed
     * @throws \Exception
     */
    public function getContentPage($slug, $options = null)
    {
        return $this->client->raw('get', "/content/content-pages/{$slug}", $options);
    }

    /**
     * Get Content Bundle.
     * Get a single content bundle.
     *
     * @param string $slug It's the string identifier generated by Mints.
     * @param array|null $options
     * @return mixed
     * @throws \Exception
     */
    public function getContentBundle($slug, $options = null)
    {
        return $this->client->raw('get', "/content/content-bundles/{$slug}", $options);
    }
}