<?php

namespace Mints\MPublic\Content;

trait PublicContentInstances
{
    /**
     * Get Content Instances.
     * Get a collection of content instances. Note: Options must be specified.
     *
     * @param array|null $options List of Resource collection options shown above can be used as parameter.
     * @return mixed
     * @throws \Exception
     */
    public function getContentInstances($options = null)
    {
        return $this->client->raw('get', '/content/content-instances', $options);
    }

    /**
     * Get Content Instance.
     * Get a single content instance.
     *
     * @param string $slug It's the string identifier generated by Mints.
     * @return mixed
     * @throws \Exception
     */
    public function getContentInstance($slug)
    {
        return $this->client->raw('get', "/content/content-instances/{$slug}");
    }
}