<?php

namespace Mints\MPublic\Content;

use Mints\MintsHelper;

trait PublicStoryVersions
{
    /**
     * Get Story Versions.
     * Get a collection of story versions.
     *
     * @param array|null $options List of Resource collection options shown above can be used as parameter.
     * @param bool $usePost Variable to determine if the request is by 'post' or 'get' functions.
     * @return mixed
     * @throws \Exception
     */
    public function getStoryVersions($options = null, $usePost = true)
    {
        return MintsHelper::getQueryResults($this->client, '/content/story-versions', $options, $usePost);
    }

    /**
     * Get Story Version.
     * Get a single story version.
     *
     * @param string $slug It's the string identifier generated by Mints.
     * @param array|null $options List of Single Resource options shown above can be used as parameter.
     * @return mixed
     * @throws \Exception
     */
    public function getStoryVersion($slug, $options = null)
    {
        return $this->client->raw('get', "/content/story-versions/{$slug}", $options);
    }
}